name: Deploy-scheduler

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Deploy_scheduler:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        CONTAINER_NAME: telegram_scheduler_bot
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        port: ${{ secrets.DEPLOY_SERVER_PORT }}
        script_stop: true
        envs: TELEGRAM_BOT_TOKEN,GOOGLE_SHEET_ID,CONTAINER_NAME
        script: |
          cd /opt/telegram_scheduler
          git pull
          docker build . -t telegram_scheduler
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
          docker run -d --restart unless-stopped --name $CONTAINER_NAME -e bot_token="$TELEGRAM_BOT_TOKEN" -e sheet_id="$GOOGLE_SHEET_ID" telegram_scheduler
          sleep 3
          docker logs $CONTAINER_NAME 2>&1 | grep 'INFO - bot starteeeed'
          
        
